# Page language (html attribute)
language: en

# Main menu navigation items
menu:
  Blog: /
  Archives: /archives

# Post social sharing features
social:
  twitter: jbreckmckye

# Page sidebars
# Components will appear in the order they are specified
sidebars:
  recent: true # boolean to display 10 most recent posts
  featured: true # boolean to list all posts with tag 'featured'
  github: jbreckmckye # string to point to a Github profile | false to disable

# Disqus comments
disqus:
  enabled: true
  shortname: breck-mckye

# Analytics
googleAnalytics: 27278071 # false | string (UA-xxxx ID)

# Link to atom.xml in nav bar?
# You can use https://github.com/hexojs/hexo-generator-feed to generate these
atom: true

# Stylesheets loaded in the <head>
stylesheets:

# Scripts loaded at the end of the body
scripts: